name: Docker Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t hello-world-app .

    - name: Run Docker container
      run: docker run hello-world-app